const data = [
  {
    name: "Grace Effiom",
    id: "LSQFf587g90",
    balance: 200000,
    tier: "1",
    accountNumber: "9912345678",
    bankName: "Providus Bank",
    phone: "07060780922",
    email: "grace@gmail.com",
    bvn: "07060780922",
    gender: "female",
    maritalStatus: "married",
    children: "none",
    typeOfResidence: "Parent’s Apartment",
    levelOfEducation: "B.Sc",
    employmentStatus: "employed",
    sectorOfEmployment: "fintech",
    durationOfEmployment: "2years",
    officialEmail: "grace@lendsqr.com",
    monthlyIncome: "₦200,000.00- ₦400,000.00",
    loanRepayment: 40000,
    twitter: "@grace_effiom",
    facebook: "Grace Effiom",
    instagram: "@grace_effiom",
    guarantors: [
      {
        name: "Debby Ogana",
        email: "debby@gmail.com",
        phone: "07060780922",
        relationship: "Sister",
      },
      {
        name: "Debby Ogana",
        email: "debby@gmail.com",
        phone: "07060780922",
        relationship: "Sister",
      },
    ],
  },
];
